<a href="https://colab.research.google.com/github/qm315Curso/python/blob/main/Clase06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
data = {
    "id":           [1, 2, 3, 4, 5, 6, 7, 8],
    "nombre":       ["Ana", "Luis", "María", "Carlos",
                     "Rosa", "Pedro", "Elena", "Jorge"],
    "facultad":     ["Ciencias", "Ingeniería", "Ciencias", "Humanidades",
                     "Ingeniería", "Ciencias", "Humanidades", "Ingeniería"],
    "publicaciones":[12, 8, 20, 5, 15, 3, 9, 18],
    "h_index":      [7, 4, 11, 3, 8, 2, 5, 10],
    "financiamiento":[45000, 28000, 72000, None, 55000,
                      12000, None, 63000],
    "anio_ingreso": [2015, 2018, 2012, 2020, 2016, 2021, 2019, 2014],
    "activo":       [True, True, True, False, True, True, True, True]
}

df = pd.DataFrame(data)
df.to_csv("output.csv",index=False)

In [6]:
url="https://raw.githubusercontent.com/qm315Curso/python/refs/heads/main/output.csv"
df=pd.read_csv(url)
df

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
0,1,Ana,Ciencias,12,7,45000,2015,True
1,2,Luis,Ingenieria,8,4,28000,2018,True
2,3,Maria,Ciencias,20,11,72000,2012,True
3,4,Carlos,Humanidades,5,3,0,2020,False
4,5,Rosa,Ingenieriia,15,8,55000,2016,True
5,6,Pedro,Ciencias,3,2,12000,2021,True
6,7,Elena,Humanidades,9,5,0,2019,True
7,8,Jorge,Ingenieria,18,10,63000,2014,True

In [14]:
print(df.shape[1])
print(df.dtypes)

8
id                 int64
nombre            object
facultad          object
publicaciones      int64
h_index            int64
financiamiento     int64
anio_ingreso       int64
activo              bool
dtype: object

In [15]:
df[["nombre","facultad","publicaciones"]]

   nombre     facultad  publicaciones
0     Ana     Ciencias             12
1    Luis   Ingenieria              8
2   Maria     Ciencias             20
3  Carlos  Humanidades              5
4    Rosa  Ingenieriia             15
5   Pedro     Ciencias              3
6   Elena  Humanidades              9
7   Jorge   Ingenieria             18

In [18]:
columnas=["activo","nombre","id"]
df[columnas]

   activo  nombre  id
0    True     Ana   1
1    True    Luis   2
2    True   Maria   3
3   False  Carlos   4
4    True    Rosa   5
5    True   Pedro   6
6    True   Elena   7
7    True   Jorge   8

In [23]:
df.iloc[0:5,1:4]

   nombre     facultad  publicaciones
0     Ana     Ciencias             12
1    Luis   Ingenieria              8
2   Maria     Ciencias             20
3  Carlos  Humanidades              5
4    Rosa  Ingenieriia             15

In [24]:
df.iloc[3:8,:]

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
3,4,Carlos,Humanidades,5,3,0,2020,False
4,5,Rosa,Ingenieriia,15,8,55000,2016,True
5,6,Pedro,Ciencias,3,2,12000,2021,True
6,7,Elena,Humanidades,9,5,0,2019,True
7,8,Jorge,Ingenieria,18,10,63000,2014,True

In [29]:
df.query("facultad == 'Ciencias'")

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
0,1,Ana,Ciencias,12,7,45000,2015,True
2,3,Maria,Ciencias,20,11,72000,2012,True
5,6,Pedro,Ciencias,3,2,12000,2021,True

In [28]:
df.query("activo==True")

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
0,1,Ana,Ciencias,12,7,45000,2015,True
1,2,Luis,Ingenieria,8,4,28000,2018,True
2,3,Maria,Ciencias,20,11,72000,2012,True
4,5,Rosa,Ingenieriia,15,8,55000,2016,True
5,6,Pedro,Ciencias,3,2,12000,2021,True
6,7,Elena,Humanidades,9,5,0,2019,True
7,8,Jorge,Ingenieria,18,10,63000,2014,True

In [31]:
df.query("publicaciones>5 and publicaciones<15")

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
0,1,Ana,Ciencias,12,7,45000,2015,True
1,2,Luis,Ingenieria,8,4,28000,2018,True
6,7,Elena,Humanidades,9,5,0,2019,True

In [33]:
df.query("facultad=='Humanidades' and anio_ingreso==2019")

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
6,7,Elena,Humanidades,9,5,0,2019,True

In [34]:
df.query("facultad not in ['Humanidades']")

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
0,1,Ana,Ciencias,12,7,45000,2015,True
1,2,Luis,Ingenieria,8,4,28000,2018,True
2,3,Maria,Ciencias,20,11,72000,2012,True
4,5,Rosa,Ingenieriia,15,8,55000,2016,True
5,6,Pedro,Ciencias,3,2,12000,2021,True
7,8,Jorge,Ingenieria,18,10,63000,2014,True

In [36]:
facultades_stem = ["Ciencias", "Ingenieria"]
df.query("facultad in @facultades_stem")

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
0,1,Ana,Ciencias,12,7,45000,2015,True
1,2,Luis,Ingenieria,8,4,28000,2018,True
2,3,Maria,Ciencias,20,11,72000,2012,True
5,6,Pedro,Ciencias,3,2,12000,2021,True
7,8,Jorge,Ingenieria,18,10,63000,2014,True

In [37]:
df.filter(like="ingreso")

   anio_ingreso
0          2015
1          2018
2          2012
3          2020
4          2016
5          2021
6          2019
7          2014

In [41]:
df.filter(regex="bre")

   nombre
0     Ana
1    Luis
2   Maria
3  Carlos
4    Rosa
5   Pedro
6   Elena
7   Jorge

In [44]:
df.select_dtypes(include=["object","bool"])

   nombre     facultad  activo
0     Ana     Ciencias    True
1    Luis   Ingenieria    True
2   Maria     Ciencias    True
3  Carlos  Humanidades   False
4    Rosa  Ingenieriia    True
5   Pedro     Ciencias    True
6   Elena  Humanidades    True
7   Jorge   Ingenieria    True

In [46]:
df2=df.drop(columns=["id", "activo"])
df2

   nombre     facultad  publicaciones  h_index  financiamiento  anio_ingreso
0     Ana     Ciencias             12        7           45000          2015
1    Luis   Ingenieria              8        4           28000          2018
2   Maria     Ciencias             20       11           72000          2012
3  Carlos  Humanidades              5        3               0          2020
4    Rosa  Ingenieriia             15        8           55000          2016
5   Pedro     Ciencias              3        2           12000          2021
6   Elena  Humanidades              9        5               0          2019
7   Jorge   Ingenieria             18       10           63000          2014

In [48]:
df.sort_values("publicaciones", ascending=True)

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
5,6,Pedro,Ciencias,3,2,12000,2021,True
3,4,Carlos,Humanidades,5,3,0,2020,False
1,2,Luis,Ingenieria,8,4,28000,2018,True
6,7,Elena,Humanidades,9,5,0,2019,True
0,1,Ana,Ciencias,12,7,45000,2015,True
4,5,Rosa,Ingenieriia,15,8,55000,2016,True
7,8,Jorge,Ingenieria,18,10,63000,2014,True
2,3,Maria,Ciencias,20,11,72000,2012,True

In [49]:
df.sort_values("h_index", ascending=False)

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
2,3,Maria,Ciencias,20,11,72000,2012,True
7,8,Jorge,Ingenieria,18,10,63000,2014,True
4,5,Rosa,Ingenieriia,15,8,55000,2016,True
0,1,Ana,Ciencias,12,7,45000,2015,True
6,7,Elena,Humanidades,9,5,0,2019,True
1,2,Luis,Ingenieria,8,4,28000,2018,True
3,4,Carlos,Humanidades,5,3,0,2020,False
5,6,Pedro,Ciencias,3,2,12000,2021,True

In [52]:
df.sort_values("nombre", ascending=True).sort_values("facultad",ascending=True)

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
0,1,Ana,Ciencias,12,7,45000,2015,True
2,3,Maria,Ciencias,20,11,72000,2012,True
5,6,Pedro,Ciencias,3,2,12000,2021,True
3,4,Carlos,Humanidades,5,3,0,2020,False
6,7,Elena,Humanidades,9,5,0,2019,True
7,8,Jorge,Ingenieria,18,10,63000,2014,True
1,2,Luis,Ingenieria,8,4,28000,2018,True
4,5,Rosa,Ingenieriia,15,8,55000,2016,True

In [55]:
df.sort_values(
    ["facultad", "nombre"],
    ascending=[True, True],
    ignore_index=True
)

,id,nombre,facultad,publicaciones,h_index,financiamiento,anio_ingreso,activo
0,1,Ana,Ciencias,12,7,45000,2015,True
1,3,Maria,Ciencias,20,11,72000,2012,True
2,6,Pedro,Ciencias,3,2,12000,2021,True
3,4,Carlos,Humanidades,5,3,0,2020,False
4,7,Elena,Humanidades,9,5,0,2019,True
5,8,Jorge,Ingenieria,18,10,63000,2014,True
6,2,Luis,Ingenieria,8,4,28000,2018,True
7,5,Rosa,Ingenieriia,15,8,55000,2016,True

In [59]:
proyectos = pd.DataFrame({
    "investigador_id": [1, 2, 3, 5, 8, 9],
    "proyecto": ["IA Médica", "IoT Agrícola", "Biodiversidad",
                 "Aguas Chiriquí", "Minería Datos", "Proyecto X"],
    "monto_usd": [30000, 15000, 42000, 28000, 55000, 10000]
})
proyectos.to_csv("proyectos.csv",index=False)